/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pooprojecto;

import Model.Medico;
import Model.Usuario;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Alvaro
 */
public class Inicio extends javax.swing.JFrame {
    private Usuario usuarioLogueado;
    
    public Inicio(Usuario User) {
        initComponents();
        this.usuarioLogueado = User;
        Nombre.setText(usuarioLogueado.getEmpleado().getNombres());
        Apellido.setText(usuarioLogueado.getEmpleado().getApellidos());
        DNI.setText(usuarioLogueado.getEmpleado().getDNI());
        Correo.setText(usuarioLogueado.getEmpleado().getCorreo());
        Telefono.setText(String.valueOf(usuarioLogueado.getEmpleado().getTelefono()));
        switch (User.getRol()){
            case "Administrador" -> {
                this.GestionEmpleados.setEnabled(true);
                this.GestiónConsultorios.setEnabled(true);
                this.GestiónPacientes.setEnabled(false);
                this.Agendaycitasmedicas.setEnabled(false);
                this.Admisiónyalta.setEnabled(false);
                this.AtenciónClínica.setEnabled(false);
                this.Ordenesanálisis.setEnabled(true);
                this.Historia.setEnabled(true);
                this.Facturacionypagos.setEnabled(false);
                this.Reportes.setEnabled(true);
            }
            case "Recepcionista" -> {
                this.GestionEmpleados.setEnabled(false);
                this.GestiónConsultorios.setEnabled(false);
                this.GestiónPacientes.setEnabled(true);
                this.Agendaycitasmedicas.setEnabled(true);
                this.Admisiónyalta.setEnabled(true);
                this.AtenciónClínica.setEnabled(false);
                this.Ordenesanálisis.setEnabled(true);
                this.Historia.setEnabled(false);
                this.Facturacionypagos.setEnabled(true);
                this.Reportes.setEnabled(false);
            }
            case "Medico" -> {
                this.GestionEmpleados.setEnabled(false);
                this.GestiónConsultorios.setEnabled(false);
                this.GestiónPacientes.setEnabled(false);
                this.Agendaycitasmedicas.setEnabled(false);
                this.Admisiónyalta.setEnabled(false);
                this.AtenciónClínica.setEnabled(true);
                this.Ordenesanálisis.setEnabled(true);
                this.Historia.setEnabled(true);
                this.Facturacionypagos.setEnabled(false);
                this.Reportes.setEnabled(false);
            }
            case "Enfermero(a)" -> {
                this.GestionEmpleados.setEnabled(false);
                this.GestiónConsultorios.setEnabled(false);
                this.GestiónPacientes.setEnabled(false);
                this.Agendaycitasmedicas.setEnabled(false);
                this.Admisiónyalta.setEnabled(true);
                this.AtenciónClínica.setEnabled(false);
                this.Ordenesanálisis.setEnabled(true);
                this.Historia.setEnabled(false);
                this.Facturacionypagos.setEnabled(false);
                this.Reportes.setEnabled(false);
            }
            case "Cajero" -> {
                this.GestionEmpleados.setEnabled(false);
                this.GestiónConsultorios.setEnabled(false);
                this.GestiónPacientes.setEnabled(false);
                this.Agendaycitasmedicas.setEnabled(false);
                this.Admisiónyalta.setEnabled(false);
                this.AtenciónClínica.setEnabled(false);
                this.Ordenesanálisis.setEnabled(true);
                this.Historia.setEnabled(false);
                this.Facturacionypagos.setEnabled(true);
                this.Reportes.setEnabled(false);
            }
            default -> throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Correo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Telefono = new javax.swing.JTextField();
        Cerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Roles = new javax.swing.JMenu();
        GestionEmpleados = new javax.swing.JMenuItem();
        GestiónConsultorios = new javax.swing.JMenuItem();
        GestiónPacientes = new javax.swing.JMenuItem();
        Agendaycitasmedicas = new javax.swing.JMenuItem();
        Admisiónyalta = new javax.swing.JMenuItem();
        AtenciónClínica = new javax.swing.JMenuItem();
        Ordenesanálisis = new javax.swing.JMenuItem();
        Historia = new javax.swing.JMenuItem();
        Facturacionypagos = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Tipo = new javax.swing.JMenuItem();
        Permisos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 477));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 477));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bienvenido");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombres:");

        Nombre.setForeground(new java.awt.Color(0, 102, 153));
        Nombre.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        Nombre.setEnabled(false);
        Nombre.setSelectionColor(new java.awt.Color(0, 102, 153));
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apellidos:");

        Apellido.setCaretColor(new java.awt.Color(0, 102, 153));
        Apellido.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        Apellido.setEnabled(false);
        Apellido.setSelectionColor(new java.awt.Color(0, 102, 153));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DNI:");

        DNI.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        DNI.setEnabled(false);
        DNI.setSelectionColor(new java.awt.Color(0, 102, 153));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Correo:");

        Correo.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        Correo.setEnabled(false);
        Correo.setSelectionColor(new java.awt.Color(0, 102, 153));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Telefono");

        Telefono.setDisabledTextColor(new java.awt.Color(0, 102, 153));
        Telefono.setEnabled(false);
        Telefono.setSelectionColor(new java.awt.Color(0, 102, 153));

        Cerrar.setForeground(new java.awt.Color(0, 102, 153));
        Cerrar.setText("Cerrar Sesion");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(Apellido)
                        .addComponent(jLabel7)
                        .addComponent(DNI)
                        .addComponent(jLabel8)
                        .addComponent(Correo)
                        .addComponent(jLabel9)
                        .addComponent(Telefono)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(Cerrar)
                                .addGap(97, 97, 97)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(Cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(400, 0, 400, 477);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 477));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 153));
        jLabel10.setText("POLICLÍNICO");

        jLabel4.setFont(new java.awt.Font("Sylfaen", 1, 68)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 153));
        jLabel4.setText("Vida y Salud");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(jLabel10)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(179, 179, 179))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jLabel10)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 400, 477);

        Roles.setText("Funciones");

        GestionEmpleados.setText("Gestion Empleados");
        GestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionEmpleadosActionPerformed(evt);
            }
        });
        Roles.add(GestionEmpleados);

        GestiónConsultorios.setText("Gestión Consultorios");
        GestiónConsultorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónConsultoriosActionPerformed(evt);
            }
        });
        Roles.add(GestiónConsultorios);

        GestiónPacientes.setText("Gestión Pacientes");
        GestiónPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestiónPacientesActionPerformed(evt);
            }
        });
        Roles.add(GestiónPacientes);

        Agendaycitasmedicas.setText("Agenda y citas médicas");
        Agendaycitasmedicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendaycitasmedicasActionPerformed(evt);
            }
        });
        Roles.add(Agendaycitasmedicas);

        Admisiónyalta.setText("Admisión y alta");
        Roles.add(Admisiónyalta);

        AtenciónClínica.setText("Atención Clínica");
        Roles.add(AtenciónClínica);

        Ordenesanálisis.setText("Ejecución de órdenes de análisis");
        Roles.add(Ordenesanálisis);

        Historia.setText("Historia Clínica y Documentos ");
        Roles.add(Historia);

        Facturacionypagos.setText("Facturación y pagos");
        Roles.add(Facturacionypagos);

        Reportes.setText("Reportes");
        Roles.add(Reportes);

        jMenuBar1.add(Roles);

        jMenu1.setText("Rol");

        Tipo.setText("Tipo");
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });
        jMenu1.add(Tipo);

        Permisos.setText("Permisos");
        Permisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermisosActionPerformed(evt);
            }
        });
        jMenu1.add(Permisos);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgendaycitasmedicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendaycitasmedicasActionPerformed
        GCitas GCitas = new GCitas();
        GCitas.setVisible(true);
        GCitas.pack();
        GCitas.setLocationRelativeTo(null);
    }//GEN-LAST:event_AgendaycitasmedicasActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        if (usuarioLogueado.getEmpleado() instanceof Medico medico) {
            JOptionPane.showMessageDialog(this,"Rol: Médico\nEspecialidad: " + medico.getEspecialidad());
        } else {
            JOptionPane.showMessageDialog(this,"Rol: " + usuarioLogueado.getRol());
        }
    }//GEN-LAST:event_TipoActionPerformed

    private void PermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermisosActionPerformed
        switch (usuarioLogueado.getRol()) {
            case "Administrador" -> {
                JOptionPane.showMessageDialog(this, "Usted cuenta con permisos para: "
                        + "empleados, consultorios/recursos, aranceles/servicios, reportes, auditoría.");
                break;
            }
            case "Recepcionista" -> {
                JOptionPane.showMessageDialog(this, "Usted cuenta con permisos para: "
                        + "pacientes, agenda/citas, admisión/alta, cobros básicos.");
                break;
            }   
            case "Medico" -> {
                JOptionPane.showMessageDialog(this, "Usted cuenta con permisos para: "
                        + "recetas, órdenes, acceso a historia clínica de sus pacientes del día.");
                break;
            }
            case "Enfermero(a)" -> {
                JOptionPane.showMessageDialog(this, "Usted cuenta con permisos para: "
                        + "signos vitales, admisión, apoyo en ejecución de órdenes");
                break;
            }
            case "Cajero" -> {
                JOptionPane.showMessageDialog(this, "Usted cuenta con permisos para: "
                        + "facturación y pagos.");
                break;
            }
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_PermisosActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed

    }//GEN-LAST:event_NombreActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(this,"¿Está seguro que desea cerrar sesión?","Confirmación",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.OK_OPTION) {
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
        this.dispose();
        }


    }//GEN-LAST:event_CerrarActionPerformed

    private void GestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionEmpleadosActionPerformed
        GEmpleado GEmpleado = new GEmpleado();
        GEmpleado.setVisible(true);
        GEmpleado.pack();
        GEmpleado.setLocationRelativeTo(null);
    }//GEN-LAST:event_GestionEmpleadosActionPerformed

    private void GestiónPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónPacientesActionPerformed
        GPacientes GPaciente = new GPacientes();
        GPaciente.setVisible(true);
        GPaciente.pack();
        GPaciente.setLocationRelativeTo(null);
    }//GEN-LAST:event_GestiónPacientesActionPerformed

    private void GestiónConsultoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestiónConsultoriosActionPerformed
        GConsultorios GConsultorio = new GConsultorios();
        GConsultorio.setVisible(true);
        GConsultorio.pack();
        GConsultorio.setLocationRelativeTo(null);
    }//GEN-LAST:event_GestiónConsultoriosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Admisiónyalta;
    private javax.swing.JMenuItem Agendaycitasmedicas;
    private javax.swing.JTextField Apellido;
    private javax.swing.JMenuItem AtenciónClínica;
    private javax.swing.JButton Cerrar;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField DNI;
    private javax.swing.JMenuItem Facturacionypagos;
    private javax.swing.JMenuItem GestionEmpleados;
    private javax.swing.JMenuItem GestiónConsultorios;
    private javax.swing.JMenuItem GestiónPacientes;
    private javax.swing.JMenuItem Historia;
    private javax.swing.JTextField Nombre;
    private javax.swing.JMenuItem Ordenesanálisis;
    private javax.swing.JMenuItem Permisos;
    private javax.swing.JMenuItem Reportes;
    private javax.swing.JMenu Roles;
    private javax.swing.JTextField Telefono;
    private javax.swing.JMenuItem Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
