/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pooprojecto;

import Model.Administrador;
import Model.Cajero;
import Model.Empleado;
import Model.Enfermero;
import Model.Medico;
import Model.Recepcionista;
import Model.Usuario;

/**
 *
 * @author Alvaro
 */
public class Start extends javax.swing.JFrame {

    public static void main(String[] args) {

        // Inicializar todo el sistema ANTES del login
        Sistema.InicializarVariables();
        CargarUsuariosPorDefecto(); // ← Aquí cargas lo que antes estaba en Start()

        Login login = new Login();
        login.setVisible(true);
        login.pack();
        login.setLocationRelativeTo(null);
    }

    private static void CargarUsuariosPorDefecto() {
        Empleado a1 = new Administrador("Alvaro Leonardo", "Paiva Yaya", "apaivay@gmail.com", "72508549", "950209689");
        Usuario u1 = new Usuario("ADM-001", "1809", "Administrador", a1);
        Sistema.gestionUsuarios.AgregarUsuario(u1);

        Empleado e1 = new Enfermero("Alonso Lorenzo", "Garcia Mantiya", "agracial@gmail.com", "15609035", "976543357");
        Usuario u2 = new Usuario("ENF-001", "1809", "Enfermero(a)", e1);
        Sistema.gestionUsuarios.AgregarUsuario(u2);

        Empleado r1 = new Recepcionista("Kiara Lorena", "Calderon Bayona", "kcalderonl@gmail.com", "72657896", "998632014");
        Usuario u3 = new Usuario("REC-001", "1809", "Recepcionista", r1);
        Sistema.gestionUsuarios.AgregarUsuario(u3);

        Empleado c1 = new Cajero("Alan Jonathan", "Ollanta Diaz", "aollantaj@gmail.com", "73695175", "969571021");
        Usuario u4 = new Usuario("CAJ-001", "1809", "Cajero", c1);
        Sistema.gestionUsuarios.AgregarUsuario(u4);

        Empleado m1 = new Medico("Angel Rodrigo", "Menendez Arriola", "amenendezm@gmail.com", "15376066", "975284369", "Pediatra");
        Usuario u5 = new Usuario("MED-001", "1809", "Medico", m1);
        Sistema.gestionUsuarios.AgregarUsuario(u5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
